import type { Location } from '../core/state/types'

export const INITIAL_MAP: Location[] = [
  {
    id: 'depot_9',
    x: 120,
    type: 'depot',
    state: 'unknown',
    name: 'Depot 9',
    shortDescription: 'A rail depot. Fuel smell in the air even from here.',
    fullDescription: `A former supply depot. The loading bays are intact. Something has been living in the supervisor's office but isn't there now. Canned goods on the shelves. Fuel in the reserve tanks.`,
    resourceLoot: { supplies: 22, fuel: 18, information: 1 },
    resonanceMultiplier: 1.0,
    annotations: [],
  },
  {
    id: 'ruin_cluster_4',
    x: 200,
    type: 'ruin',
    state: 'unknown',
    name: 'Ruin Cluster 4',
    shortDescription: 'Industrial ruins. Wrong geometry.',
    fullDescription: `A collapsed industrial zone. The buildings are structurally intact but the geometry is wrong — not in ways that can be easily explained. Photos taken here show different geometry than remembered. Resonance is amplified here.`,
    resourceLoot: { supplies: 8, information: 2 },
    resonanceMultiplier: 2.0,
    annotations: [],
  },
  {
    id: 'settlement_brightwell',
    x: 310,
    type: 'settlement',
    state: 'unknown',
    name: 'Brightwell (Formerly)',
    shortDescription: 'A town. Lights on. Nobody answers.',
    fullDescription: `The town is intact. Dinner was on the tables. Lights on. A television playing a show that stopped broadcasting four years ago. The food was brought back. The feeling was not.`,
    resourceLoot: { supplies: 18, information: 2 },
    resonanceMultiplier: 1.2,
    annotations: [],
  },
  {
    id: 'quiet_zone_11',
    x: 410,
    type: 'quiet',
    state: 'unknown',
    shortDescription: 'A location that registered on a signal. Then nothing.',
    resonanceMultiplier: 0.8,
    annotations: [],
  },
  {
    id: 'anomaly_site_1',
    x: 520,
    type: 'anomaly',
    state: 'unknown',
    shortDescription: `Something the map cannot categorize.`,
    fullDescription: `The instruments don't agree on what this is. Resonance spikes sharply on approach. The Voice goes quiet near here.`,
    resonanceMultiplier: 6.0,
    fragmentId: 'signal_theory_brief',
    annotations: [],
  },
  {
    id: 'depot_rusted',
    x: 640,
    type: 'depot',
    state: 'unknown',
    name: 'Rusted Waystation',
    shortDescription: 'A waystation. Rust. Probably fuel.',
    fullDescription: `An old waystation, long out of service. The fuel tanks are still half-full — diesel has an impressive shelf life when sealed. Something has scratched numbers into the metal walls. Not a sequence anyone recognizes.`,
    resourceLoot: { fuel: 25, supplies: 5 },
    resonanceMultiplier: 0.9,
    annotations: [],
  },
  {
    id: 'incident_site',
    x: 780,
    type: 'incident',
    state: 'unknown',
    name: '[INCIDENT SITE]',
    shortDescription: "don't.",
    fullDescription: "don't.",
    resonanceMultiplier: 3.0,
    fragmentId: 'incident_lore_major',
    annotations: [],
  },
  {
    id: 'settlement_convoy',
    x: 900,
    type: 'settlement',
    state: 'unknown',
    name: 'The Convoy (Stationary)',
    shortDescription: `A group of vehicles. People. Maybe.`,
    fullDescription: `A convoy of vehicles that stopped moving some months ago and simply stayed. They have food, water, and a working radio. They are waiting for something, they say. They don't say what.`,
    resourceLoot: { supplies: 30, information: 3 },
    resonanceMultiplier: 1.0,
    annotations: [],
  },
  {
    id: 'ruin_signal_tower',
    x: 1050,
    type: 'ruin',
    state: 'unknown',
    name: 'Signal Tower (Collapsed)',
    shortDescription: 'A broadcast tower. Mostly down.',
    fullDescription: `A collapsed broadcast tower. The transmitter is still active, somehow — broadcasting on a frequency that's all wrong for the hardware. Documents in the control room reference a project that has no acronym expansion in any surviving record.`,
    resourceLoot: { information: 4, power: 10 },
    resonanceMultiplier: 2.5,
    fragmentId: 'weapon_theory_notes',
    annotations: [],
  },
  {
    id: 'anomaly_deep_2',
    x: 1200,
    type: 'anomaly',
    state: 'unknown',
    shortDescription: `Instruments disagree. The Voice said nothing when asked.`,
    resonanceMultiplier: 6.0,
    fragmentId: 'old_presence_fragment',
    annotations: [],
  },
  {
    id: 'origin_point',
    x: 1500,
    type: 'anomaly',
    state: 'unknown',
    name: '[ ? ? ? ]',
    shortDescription: 'End of map. Or beginning.',
    resonanceMultiplier: 1.0,
    annotations: [],
  },
]
